ALTER TABLE DETSALES ADD 
ENTID integer;

COMMIT;
UPDATE DETSALES 
SET ENTID = ENTRYID;

COMMIT;

ALTER TABLE DETSALES ALTER ENTID POSITION 1;
ALTER TABLE DETSALES ALTER ENTRYID POSITION 2;
ALTER TABLE DETSALES ALTER SALEID POSITION 3;
ALTER TABLE DETSALES ALTER ITEMNAME POSITION 4;
ALTER TABLE DETSALES ALTER QUANTITY POSITION 5;
ALTER TABLE DETSALES ALTER AMOUNTDUE POSITION 6;

COMMIT;

ALTER TABLE DETSALES DROP ENTRYID;

COMMIT;

ALTER TABLE DETSALES ALTER ENTID TO ENTRYID;